{
 "title": "NGINX / API / Host",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ERROR 3XX - 1min",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_3XX{host=~\"$host\"}",
       "legendFormat": "3XX - 1min - {{endpoint}} "
      }
     ]
    },
    {
     "title": "2XX QPS By Instance",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_2XX{host=~\"$host\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ERROR Rate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds_sum:err_rate_by_host_endpoint{host=~\"$host\"} > 0.01",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "ERROR 4XX - 1min",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_4XX{host=~\"$host\"}",
       "legendFormat": "4XX - 1min - {{endpoint}}"
      }
     ]
    },
    {
     "title": "4XX QPS By Instance",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_4XX{host=~\"$host\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "2XX Latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds:p999_by_host_2XX{host=~\"[[host]]\"}",
       "legendFormat": "2XX-P999"
      },
      {
       "expr": "job:nginx_http_request_duration_seconds:p99_by_host_2XX{host=~\"[[host]]\"}",
       "legendFormat": "2XX-P99"
      },
      {
       "expr": "job:nginx_http_request_duration_seconds:p90_by_host_2XX{host=~\"[[host]]\"}",
       "legendFormat": "2XX-P90"
      },
      {
       "expr": "job:nginx_http_request_duration_seconds:avg_by_host_2XX{host=~\"[[host]]\"}",
       "legendFormat": "2XX-AVG"
      }
     ]
    },
    {
     "title": "ERROR 5XX - 1min",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_5XX{host=~\"$host\"}",
       "legendFormat": "5XX - 1min - {{endpoint}}"
      }
     ]
    },
    {
     "title": "5XX QPS By Instance",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_5XX{host=~\"$host\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (host) (job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX{host=~\"$host\"})",
       "legendFormat": "2XX"
      },
      {
       "expr": "sum by (host) (job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_4XX{host=~\"$host\"})",
       "legendFormat": "4XX"
      },
      {
       "expr": "sum by (host) (job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_5XX{host=~\"$host\"})",
       "legendFormat": "5XX"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOP 10 QPS",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "topk(10, avg(job:nginx_http_request_duration_seconds:qps_by_host_endpoint_2XX{host=~\"$host\"}) by (endpoint))"
      }
     ]
    },
    {
     "title": "TOP 10 4XX - 1min",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "topk(10, sum(job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_4XX{host=~\"$host\"}) by (endpoint)>0)"
      }
     ]
    },
    {
     "title": "TOP 10 5XX - 1min",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "topk(10, sum(job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_5XX{host=~\"$host\"}) by (endpoint)>0)"
      }
     ]
    }
   ]
  },
  { "title": "URL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "TOP 10 QPS",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, sum by(endpoint,fullurl) (job:nginx_http_request_duration_seconds:qps_by_host_endpoint_fullurl_2XX{host=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "TOP 10 4XX - 1min",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, sum(job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_fullurl_4XX{host=~\"$host\"}) by (endpoint, fullurl)>0)"
    }
   ]
  },
  {
   "title": "TOP 10 5XX - 1min",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, sum(job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_fullurl_5XX{host=~\"$host\"}) by (endpoint,fullurl)>0)"
    }
   ]
  }
 ]
}