{
 "title": "NGINX / API / Host / Endpoint",
 "tags": [ "nginx" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX, host)"
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "label_values(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX{host=~\"$host\"}, endpoint)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR 3XX - 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_fullurl_3XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "3XX - 1min - {{fullurl}} "
    }
   ]
  },
  {
   "title": "2XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_2XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "2XX"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_4XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "4XX"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_5XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "ERROR 4XX - 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_fullurl_4XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "4XX - 1min - {{fullurl}} "
    }
   ]
  },
  {
   "title": "4XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_4XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p999_by_host_endpoint_2XX{host=~\"[[host]]\", endpoint=~\"$endpoint\"}",
     "legendFormat": "2XX-P999"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p99_by_host_endpoint_2XX{host=~\"[[host]]\", endpoint=~\"$endpoint\"}",
     "legendFormat": "2XX-P99"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p90_by_host_endpoint_2XX{host=~\"[[host]]\", endpoint=~\"$endpoint\"}",
     "legendFormat": "2XX-P90"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:avg_by_host_endpoint_2XX{host=~\"[[host]]\", endpoint=~\"$endpoint\"}",
     "legendFormat": "2XX-AVG"
    }
   ]
  },
  {
   "title": "ERROR 5XX - 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_fullurl_5XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "5XX - 1min - {{fullurl}} "
    }
   ]
  },
  {
   "title": "5XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_5XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ERROR Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds_sum:err_rate_by_host_endpoint_fullurl{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{fullurl}}"
    }
   ]
  },
  { "title": "URL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "TOP 10 QPS",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by(fullurl) (job:nginx_http_request_duration_seconds:qps_by_host_endpoint_fullurl_2XX{host=~\"$host\", endpoint=~\"$endpoint\"}))"
    }
   ]
  },
  {
   "title": "TOP 10 4XX - 1min",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum(job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_fullurl_4XX{host=~\"$host\", endpoint=~\"$endpoint\"}) by (fullurl)>0)"
    }
   ]
  },
  {
   "title": "TOP 10 5XX - 1min",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum(job:nginx_http_request_duration_seconds_count:counter_1min_by_host_endpoint_fullurl_5XX{host=~\"$host\", endpoint=~\"$endpoint\"}) by (fullurl)>0)"
    }
   ]
  }
 ]
}